const DEFAULT_CORS_ORIGIN = 'http://localhost:3000'
const DEFAULT_PORT = 5001
const REQUEST_BODY_LIMIT = '1mb'

const LOGIN_PASSWORD_MIN_LENGTH = 6
const PASSWORD_MIN_LENGTH = 8
const NAME_MIN_LENGTH = 2
const REVIEW_RATING_MIN = 1
const REVIEW_RATING_MAX = 5
const REVIEW_COMMENT_MIN_LENGTH = 3

const PASSWORD_SALT_ROUNDS = 10
const DEFAULT_SHIPPING_PRICE = 10
const DEFAULT_UPLOAD_SIZE_BYTES = 2 * 1024 * 1024

const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000
const API_RATE_LIMIT = { production: 200, development: 500 }
const AUTH_RATE_LIMIT = { production: 10, development: 30 }
const REVIEW_RATE_LIMIT = { production: 20, development: 50 }
const UPLOAD_RATE_LIMIT = { production: 10, development: 30 }

export {
  DEFAULT_CORS_ORIGIN,
  DEFAULT_PORT,
  REQUEST_BODY_LIMIT,
  LOGIN_PASSWORD_MIN_LENGTH,
  PASSWORD_MIN_LENGTH,
  NAME_MIN_LENGTH,
  REVIEW_RATING_MIN,
  REVIEW_RATING_MAX,
  REVIEW_COMMENT_MIN_LENGTH,
  PASSWORD_SALT_ROUNDS,
  DEFAULT_SHIPPING_PRICE,
  DEFAULT_UPLOAD_SIZE_BYTES,
  RATE_LIMIT_WINDOW_MS,
  API_RATE_LIMIT,
  AUTH_RATE_LIMIT,
  REVIEW_RATE_LIMIT,
  UPLOAD_RATE_LIMIT,
}
